#!/usr/bin/env python3
"""Generate the profile's first-party verification badge array.

The large counters come from ``assets/summary.json``, which is regenerated by
``scripts/telemetry.py`` from the public repository source.  The capability
chips are labels, not certifications or GitHub-issued achievements.  Live
build status stays in GitHub's own workflow badges in the README.

    python3 scripts/badges.py
"""

import json
from pathlib import Path

W = 1200
H = 346
PAD = 42
MONO = "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace"
SANS = "Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"

DARK = {
    "name": "dark", "bg": "#050814", "panel": "#0a1020",
    "panel2": "#0d1628", "line": "#20314d", "text": "#f4f8ff",
    "muted": "#8da2bf", "cyan": "#4de7ff", "blue": "#4f8cff",
    "violet": "#9b7bff", "amber": "#ffcb66", "green": "#68f5ae",
}
LIGHT = {
    "name": "light", "bg": "#f7fbff", "panel": "#ffffff",
    "panel2": "#eef5ff", "line": "#c4d5ea", "text": "#0b1730",
    "muted": "#526a88", "cyan": "#007d9d", "blue": "#145fe0",
    "violet": "#7048d7", "amber": "#9b6400", "green": "#087a4c",
}

CAPABILITIES = [
    "C++17", "PYTHON", "RAFT", "MVCC", "SIMD",
    "HNSW", "EDGAR", "XBRL", "SAR", "VIO",
]


def load_summary():
    try:
        data = json.loads(Path("assets/summary.json").read_text())
        return {
            "repos": int(data["repos"]),
            "tests": int(data["tests"]),
            "bytes": int(data["bytes"]),
            "languages": int(data.get("languages", 0)),
            "generated": str(data["generated"]),
        }
    except (FileNotFoundError, KeyError, TypeError, ValueError, json.JSONDecodeError):
        return {"repos": 0, "tests": 0, "bytes": 0,
                "languages": 0, "generated": "unknown"}


def esc(value):
    return (str(value).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def card(x, title, value, label, colour, index, theme):
    width = 170
    delay = 0.08 * index
    return f"""
    <g class="card" style="animation-delay:{delay:.2f}s">
      <rect x="{x}" y="92" width="{width}" height="118" rx="11"
            fill="{theme['panel']}" stroke="{theme['line']}"/>
      <path d="M{x+1} 118H{x+width-1}" stroke="{theme['line']}"/>
      <path d="M{x+12} 92H{x+54}" stroke="{colour}" stroke-width="2.5"/>
      <circle cx="{x+148}" cy="106" r="4" fill="{colour}" class="pulse"/>
      <text x="{x+14}" y="111" class="mono micro" fill="{theme['muted']}">{esc(title)}</text>
      <text x="{x+14}" y="163" class="sans value" fill="{colour}">{esc(value)}</text>
      <text x="{x+14}" y="190" class="mono label" fill="{theme['text']}">{esc(label)}</text>
      <rect x="{x+14}" y="198" width="{width-28}" height="2" rx="1" fill="{theme['line']}"/>
      <rect x="{x+14}" y="198" width="{42 + index*13}" height="2" rx="1"
            fill="{colour}" class="meter" style="animation-delay:{delay+.35:.2f}s"/>
    </g>"""


def build(theme, data):
    source_kb = round(data["bytes"] / 1024)
    cards = [
        ("SYSTEMS", f"{data['repos']:02d}", "PUBLIC BUILDS", theme["cyan"]),
        ("TEST SURFACE", f"{data['tests']:,}", "FUNCTIONS", theme["green"]),
        ("SOURCE", f"{source_kb:,}K", "COUNTED BYTES", theme["violet"]),
        ("LANGUAGES", f"{data['languages']:02d}", "BY SOURCE", theme["blue"]),
        ("LIVE LABS", "04", "INTERACTIVE", theme["amber"]),
        ("PROOF MODE", "CI", "ORACLE + BENCH", theme["cyan"]),
    ]
    xs = [42, 228, 414, 600, 786, 972]
    card_markup = "".join(
        card(x, title, value, label, colour, i, theme)
        for i, (x, (title, value, label, colour)) in enumerate(zip(xs, cards))
    ).strip()

    chip_gap = 9
    chip_width = (W - 2 * PAD - chip_gap * (len(CAPABILITIES) - 1)) / len(CAPABILITIES)
    chips = []
    x = PAD
    colours = [theme["cyan"], theme["blue"], theme["violet"],
               theme["green"], theme["amber"]]
    for i, name in enumerate(CAPABILITIES):
        colour = colours[i % len(colours)]
        chips.append(
            f'<g class="chip" style="animation-delay:{0.55+i*0.045:.3f}s">'
            f'<rect x="{x:.1f}" y="244" width="{chip_width:.1f}" height="34" rx="17" '
            f'fill="{theme["panel"]}" stroke="{theme["line"]}"/>'
            f'<circle cx="{x+15:.1f}" cy="261" r="3" fill="{colour}"/>'
            f'<text x="{x+25:.1f}" y="265" class="mono chip-text" fill="{theme["text"]}">{name}</text>'
            f'</g>'
        )
        x += chip_width + chip_gap

    aria = (f"Verification badge array: {data['repos']} public systems, "
            f"{data['tests']} test functions, {source_kb} kilobytes of source, "
            f"{data['languages']} languages, four interactive labs, and live CI.")
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="{esc(aria)}">
  <defs>
    <linearGradient id="bg-{theme['name']}" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{theme['bg']}"/>
      <stop offset=".52" stop-color="{theme['panel']}"/>
      <stop offset="1" stop-color="{theme['panel2']}"/>
    </linearGradient>
    <linearGradient id="scan-{theme['name']}" x1="0" x2="1">
      <stop stop-color="{theme['cyan']}" stop-opacity="0"/>
      <stop offset=".5" stop-color="{theme['cyan']}" stop-opacity=".35"/>
      <stop offset="1" stop-color="{theme['cyan']}" stop-opacity="0"/>
    </linearGradient>
    <pattern id="grid-{theme['name']}" width="22" height="22" patternUnits="userSpaceOnUse">
      <path d="M22 0H0V22" fill="none" stroke="{theme['muted']}" stroke-opacity=".055"/>
    </pattern>
  </defs>
  <style>
    .mono {{ font-family: {MONO}; }}
    .sans {{ font-family: {SANS}; }}
    .micro {{ font-size:10px; letter-spacing:1.5px; }}
    .value {{ font-size:34px; font-weight:760; letter-spacing:-1px; }}
    .label {{ font-size:10px; letter-spacing:1.25px; }}
    .chip-text {{ font-size:10px; font-weight:650; letter-spacing:.45px; }}
    .card,.chip {{ animation:enter .65s cubic-bezier(.18,.78,.28,1) backwards; }}
    .pulse {{ animation:pulse 2.4s ease-in-out infinite; transform-box:fill-box; transform-origin:center; }}
    .meter {{ animation:meter .9s cubic-bezier(.16,.84,.34,1) backwards; transform-box:fill-box; transform-origin:left center; }}
    .scanner {{ animation:scanline 7s ease-in-out infinite; }}
    @keyframes enter {{ from {{ transform:translateY(8px); }} }}
    @keyframes pulse {{ 0%,100% {{ opacity:.35; transform:scale(.8); }} 50% {{ opacity:1; transform:scale(1.25); }} }}
    @keyframes meter {{ from {{ transform:scaleX(0); }} }}
    @keyframes scanline {{ 0%,100% {{ transform:translateX(-220px); opacity:0; }} 12%,88% {{ opacity:.8; }} 100% {{ transform:translateX(1300px); }} }}
    @media (prefers-reduced-motion: reduce) {{
      .card,.chip,.pulse,.meter {{ animation:none; }} .scanner {{ display:none; }}
    }}
  </style>
  <rect width="{W}" height="{H}" rx="16" fill="url(#bg-{theme['name']})"/>
  <rect width="{W}" height="{H}" rx="16" fill="url(#grid-{theme['name']})"/>
  <rect x=".75" y=".75" width="{W-1.5}" height="{H-1.5}" rx="15.25" fill="none" stroke="{theme['line']}" stroke-width="1.5"/>

  <text x="{PAD}" y="43" class="sans" font-size="21" font-weight="740" letter-spacing=".7" fill="{theme['text']}">SYSTEM CREDENTIAL ARRAY</text>
  <text x="{PAD}" y="66" class="mono" font-size="11" letter-spacing="1.4" fill="{theme['muted']}">NON-AWARD BADGES // GENERATED FROM PUBLIC SOURCE</text>
  <circle cx="1007" cy="43" r="4" fill="{theme['green']}" class="pulse"/>
  <text x="1020" y="47" class="mono" font-size="10.5" letter-spacing="1.1" fill="{theme['green']}">SOURCE VERIFIED</text>

  {card_markup}
  {''.join(chips)}

  <line x1="{PAD}" y1="302" x2="{W-PAD}" y2="302" stroke="{theme['line']}"/>
  <text x="{PAD}" y="325" class="mono" font-size="10.5" letter-spacing="1.25" fill="{theme['muted']}">LIVE BUILD CHANNELS BELOW ↓</text>
  <text x="{W-PAD}" y="325" text-anchor="end" class="mono" font-size="10.5" fill="{theme['muted']}">REFRESHED {esc(data['generated'])}</text>
  <rect class="scanner" x="-220" y="82" width="220" height="128" fill="url(#scan-{theme['name']})"/>
</svg>
"""


def main():
    data = load_summary()
    if not data["repos"] or not data["tests"]:
        raise SystemExit("summary metrics are empty; run scripts/telemetry.py first")
    Path("assets").mkdir(exist_ok=True)
    for theme in (DARK, LIGHT):
        path = Path(f"assets/credentials-{theme['name']}.svg")
        path.write_text(build(theme, data))
        print(f"wrote {path} ({path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
